#!/bin/bash

if [[ $# -eq 0 ]];
then
    echo "Enter domain target "
    exit 1
fi

url=$1

if [ ! -d "/tmp/$url" ];then
        mkdir /tmp/$url
fi
if [ ! -d "~/recon/$url" ];then
        mkdir ~/recon/$url
fi
if [ ! -d "~/recon/$url/subdomains" ];then
        mkdir ~/recon/$url/subdomains
fi

if [ ! -f "~/recon/$url/subdomains/virustotalSubdomain" ];then
        touch ~/recon/$url/subdomains/virustotalSubdomain
fi

if [ ! -f "~/recon/$url/subdomains/subfinder" ];then
        touch ~/recon/$url/subdomains/subfinder
fi

if [ ! -f "~/recon/$url/subdomains/assetfinder" ];then
        touch ~/recon/$url/subdomains/assetfinder
fi
if [ ! -f "~/recon/$url/subdomains/gau" ];then
        touch ~/recon/$url/subdomains/gau
fi
if [ ! -f "~/recon/$url/subdomains/githubSearch" ];then
        touch ~/recon/$url/subdomains/githubSearch
fi
if [ ! -f "~/recon/$url/subdomains/ctl" ];then
        touch ~/recon/$url/subdomains/ctl
fi
if [ ! -f "~/recon/$url/subdomains/abuseipdb" ];then
        touch ~/recon/$url/subdomains/abuseipdb
fi

if [ ! -f "~/recon/$url/subdomains/amass" ];then
        touch ~/recon/$url/subdomains/amass
fi

if [ ! -f "~/recon/$url/subdomains/gospider" ];then
        touch ~/recon/$url/subdomains/gospider
fi
if [ ! -f "~/recon/$url/subdomains/shuffleDNS" ];then
        touch ~/recon/$url/subdomains/shuffleDNS
fi
if [ ! -f "~/recon/$url/subdomains/consolidated" ];then
        touch ~/recon/$url/subdomains/consolidated
fi
if [ ! -f "~/recon/$url/subdomains/dnsgen" ];then
        touch ~/recon/$url/subdomains/dnsgen
fi

if [ ! -f "~/recon/$url/subdomains/httprobe" ];then
        touch ~/recon/$url/subdomains/httprobe
fi


if [ ! -f "~/recon/$url/subdomains/gau" ];then
        touch ~/recon/$url/subdomains/gau
fi
if [ ! -f "~/recon/$url/subdomains/findomain" ];then
        touch ~/recon/$url/subdomains/findomain
fi
if [ ! -f "~/recon/$url/subdomains/cero" ];then
        touch ~/recon/$url/subdomains/cero
fi



echo -e "\e[1;31m [+] Launching Virustotal Subdomain Scrape to check for subdomains \e[0m"
python3 ~/tools/virustotal-subdomain-scraper/vt-subdomains.py  $url | anew /tmp/$url/virustotalSubdomain
cat /tmp/$url/virustotalSubdomain | anew ~/recon/$url/subdomains/virustotalSubdomain
rm -rf /tmp/$url/virustotalSubdomain
echo ""

echo -e "\e[1;31m [+] Launching subfinder  to check for subdomains \e[0m"
subfinder -d $url -o /tmp/$url/subfinder
cat /tmp/$url/subfinder | anew ~/recon/$url/subdomains/subfinder
rm -rf /tmp/$url/subfinder
echo ""

echo -e "\e[1;31m [+] Launching subfinder recursive  to check for subdomains \e[0m"
subfinder -d $url  -recursive -o /tmp/$url/subfinder
cat /tmp/$url/subfinder | anew ~/recon/$url/subdomains/subfinder
rm -rf /tmp/$url/subfinder
echo ""

echo -e "\e[1;31m [+] Launching assetfinder  to check for subdomains \e[0m"
assetfinder --subs-only $url > /tmp/$url/assetfinder
cat /tmp/$url/assetfinder | anew ~/recon/$url/subdomains/assetfinder
rm -rf /tmp/$url/assetfinder
echo ""

echo -e "\e[1;31m [+] Launching gau  to check for subdomains \e[0m"
gau --subs $url | cut -d / -f3 | sort -u  > /tmp/$url/gau
cat /tmp/$url/gau | anew  ~/recon/$url/subdomains/gau
rm -rf /tmp/$url/gau
echo ""

echo -e "\e[1;31m [+] Launching  github-subdomain  to check for subdomains \e[0m"
source ~/.bashrc
github-subdomains -d $url -t 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
cat $url.txt | anew ~/recon/$url/subdomains/githubSearch
rm -rf $url.txt
echo ""

echo -e "\e[1;31m [+] Launching crt.sh to check for subdomains \e[0m"
curl -s https://crt.sh/\?q=$url\&output\=json| jq -r '.[].common_name' |sed 's/\*.//g' | sort -u > /tmp/$url/ctl
sort -u /tmp/$url/ctl | anew ~/recon/$url/subdomains/ctl
rm -rf /tmp/$url/ctl
echo ""

echo -e "\e[1;31m [+] Launching findomain  to check for subdomains \e[0m"
findomain --quiet --target $url 1> /tmp/$url/findomain 2>/dev/null
sort -u /tmp/$url/findomain | anew ~/recon/$url/subdomains/findomain
rm -rf /tmp/$url/findomain
echo ""

echo -e "\e[1;31m [+] Launching abuseipdb to check for subdomains \e[0m"
curl -s "https://www.abuseipdb.com/whois/$1" -H "user-agent: Chrome" | grep -E '<li>\w.*</li>'| grep -o '<li>.*</li>' | sed -e 's/<[^>]*>//g'| sed "s/$/.$1/g" > /tmp/$url/abuseipdb
sort -u /tmp/$url/abuseipdb | anew ~/recon/$url/subdomains/abuseipdb
rm -rf /tmp/$url/abuseipdb
echo ""

echo -e "\e[1;31m [+] Launching amass  to Discover targets for enumerations \e[0m"
amass enum -src -ip -brute -ipv4 -min-for-recursive 2 -timeout 60 -d $url > /tmp/$url/amass
sed -i -E 's/\[(.*?)\] +//g' /tmp/$url/amass
sed -i -E 's/ ([0-9]{1,3}\.)[0-9].*//g' /tmp/$url/amass
cat /tmp/$url/amass | anew ~/recon/$url/subdomains/amass
rm -rf /tmp/$url/amass
echo ""

echo -e "\e[1;31m [+] Launching gospider  to check for subdomains \e[0m"
gospider -s "https://$url" -o /tmp/$url/gospider -c 10 -d 1 --other-source --subs --include-subs
outputFile=`echo $url | sed 's/\./_/g'`
cat /tmp/$url/gospider/$outputFile | cut -d " " -f 3 | cut -d "/" -f 3 | grep $url | sort -u | anew  ~/recon/$url/subdomains/gospider
rm -rf /tmp/$url/gospider
echo ""


echo -e "\e[1;31m [+] Launching OneForAll  to find subdomains \e[0m"
rm -rf ~/tools/OneForAll/results/$url.csv
python3 ~/tools/OneForAll/oneforall.py --target $url run 
cat  ~/tools/OneForAll/results/$url.csv | cut -d "," -f 6 | anew ~/recon/$url/subdomains/OneForAll
echo ""

echo -e "\e[1;31m [+] Launching AORT  to find subdomains \e[0m"
python3 ~/tools/AORT/AORT.py -d $url --quiet --output /tmp/$url/$url-AORT.txt       
cat  /tmp/$url/$url-AORT.txt | sed 's/*\.//g' | anew ~/recon/$url/subdomains/AORT.txt
rm -rf /tmp/$url/$url-AORT.txt
echo ""

echo -e "\e[1;31m [+]  Recursive Enumeration \e[0m"
rm -rf  /tmp/$url/consolidat
cd ~/recon/$url/subdomains
ls | while read subs;do cat $subs | grep "$url" | anew  /tmp/$url/consolidat;done
cd -
cat /tmp/$url/consolidat > subdomains.txt
subdomain_list="subdomains.txt"
for sub in $( ( cat $subdomain_list | rev | cut -d '.' -f 3,2,1 | rev | sort | uniq -c | sort -nr | grep -v '1 ' | head -n 10 && cat subdomains.txt | rev | cut -d '.' -f 4,3,2,1 | rev | sort | uniq -c | sort -nr | grep -v '1 ' | head -n 10 ) | sed -e 's/^[[:space:]]*//' | cut -d ' ' -f 2);do 
    subfinder -d $sub -silent -max-time 2 | anew -q /tmp/$url/passive_recursive.txt
    assetfinder --subs-only $sub | anew -q /tmp/$url/passive_recursive.txt
    amass enum -timeout 2 -passive -d $sub | anew -q /tmp/$url/passive_recursive.txt
    findomain --quiet -t $sub | anew -q /tmp/$url/passive_recursive.txt
done
cat /tmp/$url/passive_recursive.txt | sed 's/^*\.//g' | anew ~/recon/$url/subdomains/passive_recursive.txt
rm -rf /tmp/$url/passive_recursive.txt
rm -rf /tmp/$url/consolidat
rm -rf subdomains.txt
echo ""

echo -e "\e[1;31m [+]  DNS Brute Forcing \e[0m"

echo -e "\e[1;31m [+]  shuffleDNS  to enumerate valid subdomains \e[0m"
shuffledns -d $url -r ~/wordlist/resolvers.txt -w ~/wordlist/2m-subdomains.txt  -m ~/massdns/./bin/massdns -o /tmp/$url/shuffleDNS
cat /tmp/$url/shuffleDNS | anew ~/recon/$url/subdomains/shuffleDNS
rm -rf /tmp/$url/shuffleDNS
echo ""


echo -e "\e[1;31m [+]  puredns  to bruteforce  subdomains \e[0m"
puredns bruteforce ~/wordlist/best-dns-wordlist.txt $url -r ~/wordlist/resolvers-trusted.txt --bin ~/massdns/./bin/massdns -w /tmp/$url/puredns.txt
cat /tmp/$url/puredns.txt | anew ~/recon/$url/subdomains/puredns.txt
rm -rf /tmp/$url/puredns.txt
echo ""


echo -e "\e[1;31m [+]  Launching DNSGen  to generate lists of domain names . \e[0m"
rm -rf  /tmp/$url/consolidat
cd ~/recon/$url/subdomains
ls | while read subs;do cat $subs | grep "$url" | anew  /tmp/$url/consolidat;done
cd -
puredns resolve /tmp/$url/consolidat -r ~/wordlist/resolvers-trusted.txt --bin ~/massdns/./bin/massdns  > /tmp/$url/resolved_consolidat
dnsgen  /tmp/$url/resolved_consolidat | shuffledns -d $url -r ~/wordlist/resolvers.txt  -m ~/massdns/./bin/massdns -o /tmp/$url/permute1_tmp.txt &>/dev/null
cat /tmp/$url/permute1_tmp.txt | grep -F ".$url" > /tmp/$url/permute1.txt 
dnsgen /tmp/$url/permute1.txt  | shuffledns -d $url -r ~/wordlist/resolvers.txt -m ~/massdns/./bin/massdns -o /tmp/$url/permute2_tmp.txt &>/dev/null
cat /tmp/$url/permute2_tmp.txt | grep -F ".$url" > /tmp/$url/permute2.txt
cat /tmp/$url/permute1.txt /tmp/$url/permute2.txt | grep -F ".$url" | sort -u > /tmp/$url/sort-dnsgen-new_consolidat
cat /tmp/$url/sort-dnsgen-new_consolidat | anew   ~/recon/$url/subdomains/dnsgen
rm -rf /tmp/$url/sort-dnsgen-new_consolidat
rm -rf /tmp/$url/permute1_tmp.txt 
rm -rf /tmp/$url/permute2_tmp.txt
rm -rf /tmp/$url/permute1.txt 
rm -rf /tmp/$url/permute2.txt
rm -rf /tmp/$url/consolidat
rm -rf /tmp/$url/resolved_consolidat
echo ""

echo -e "\e[1;31m [+] Permutations \e[0m"

rm -rf /tmp/$url/consolidat
cd ~/recon/$url/subdomains
ls | while read subs;do cat $subs | grep "$url" | anew  /tmp/$url/consolidat;done 
cd -
gotator -sub  /tmp/$url/consolidat -perm ~/wordlist/dns_permutations_list.txt -depth 1 -numbers 10 -mindup -adv -md | sort -u > /tmp/$url/perms.txt
puredns resolve /tmp/$url/perms.txt -r ~/wordlist/resolvers-trusted.txt --bin ~/massdns/./bin/massdns  > /tmp/$url/resolved_perms
cat /tmp/$url/resolved_perms | anew  ~/recon/$url/subdomains/permutations.txt
rm -rf /tmp/$url/perms.txt
rm -rf /tmp/$url/resolved_perms
rm -rf /tmp/$url/consolidat
echo ""


echo -e "\e[1;31m [+] Launching cero  to check for subdomains \e[0m"
rm -rf  /tmp/$url/consolidat
cd ~/recon/$url/subdomains
ls | while read subs;do cat $subs | grep "$url" | anew  /tmp/$url/consolidat;done
cd -
cat  /tmp/$url/consolidat | cero  | sed 's/*\.//g' | grep -F ".$url" > /tmp/$url/cero
sort -u /tmp/$url/cero | anew ~/recon/$url/subdomains/cero
rm -rf /tmp/$url/cero
rm -rf /tmp/$url/consolidat
echo ""

echo -e "\e[1;31m [+] TLS, CSP, CNAME Probing \e[0m"
rm -rf  /tmp/$url/consolidat
cd ~/recon/$url/subdomains
ls | while read subs;do cat $subs | grep "$url" | anew  /tmp/$url/consolidat;done
cd -
cat /tmp/$url/consolidat | httpx -csp-probe -status-code -retries 2 -no-color | anew csp_probed.txt | cut -d ' ' -f1 | unfurl -u domains | anew  /tmp/$url/csp_subdomains.txt
dnsx -retry 3 -cname -l /tmp/$url/consolidat > /tmp/$url/cname-sub.txt
cat /tmp/$url/csp_subdomains.txt  |anew  ~/recon/$url/subdomains/csp_subdomains.txt
cat  /tmp/$url/cname-sub.txt |anew  ~/recon/$url/subdomains/cname-sub.txt
rm -rf /tmp/$url/csp_subdomains.txt
rm -rf csp_probed.txt 
rm -rf /tmp/$url/cname-sub.txt
echo ""

echo -e "\e[1;31m [+] httprobe is a fast and multi-purpose HTTP toolkit that allows running multiple probes using the retryablehttp library. \e[0m"
rm -rf /tmp/$url/consolidat
cd ~/recon/$url/subdomains
ls | while read subs;do cat $subs | anew  /tmp/$url/consolidat;done
cd -
cat /tmp/$url/consolidat | grep "$url" | anew  ~/recon/$url/subdomains/consolidat

httpx -l /tmp/$url/consolidat -silent -timeout 20 -o /tmp/$url/sub.httpx &>/dev/null
httpx -l /tmp/$url/consolidat -csp-probe -silent -timeout 20 | grep -F ".$url" | anew /tmp/$url/sub.httpx &>/dev/null
httpx -l /tmp/$url/consolidat -tls-probe -silent -timeout 20 | grep -F ".$url" | anew /tmp/$url/sub.httpx &>/dev/null
cat /tmp/$url/sub.httpx > /tmp/$url/httprobe_results

cat /tmp/$url/httprobe_results > ~/recon/$url/subdomains/httprobe
cat ~/recon/$url/subdomains/httprobe >> /tmp/$url/wilcard-subs

rm -rf /tmp/$url/httprobe_results
rm -rf /tmp/$url/consolidat
rm -rf /tmp/$url/httprobeAdded
rm -rf /tmp/$url/sub.httpx
rm -rf /tmp/$url/httprobeRemoved
rm -rf /tmp/$url/previous_httprobe
echo ""






echo -e "\e[1;32m[+] Recon Stage Completed :) \e[0m"

